// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.languages;

import com.woomii.beta.frontend.languages.Languages;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Languages_Roo_Configurable {
    
    declare @type: Languages: @Configurable;
    
}
