// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.areas;

import com.woomii.beta.frontend.areas.Areas;
import com.woomii.beta.frontend.areas.AreasDataOnDemand;
import com.woomii.beta.frontend.areas.AreasIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AreasIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AreasIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AreasIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AreasIntegrationTest: @Transactional;
    
    @Autowired
    AreasDataOnDemand AreasIntegrationTest.dod;
    
    @Test
    public void AreasIntegrationTest.testCountAreases() {
        Assert.assertNotNull("Data on demand for 'Areas' failed to initialize correctly", dod.getRandomAreas());
        long count = Areas.countAreases();
        Assert.assertTrue("Counter for 'Areas' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AreasIntegrationTest.testFindAreas() {
        Areas obj = dod.getRandomAreas();
        Assert.assertNotNull("Data on demand for 'Areas' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Areas' failed to provide an identifier", id);
        obj = Areas.findAreas(id);
        Assert.assertNotNull("Find method for 'Areas' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Areas' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AreasIntegrationTest.testFindAllAreases() {
        Assert.assertNotNull("Data on demand for 'Areas' failed to initialize correctly", dod.getRandomAreas());
        long count = Areas.countAreases();
        Assert.assertTrue("Too expensive to perform a find all test for 'Areas', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Areas> result = Areas.findAllAreases();
        Assert.assertNotNull("Find all method for 'Areas' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Areas' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AreasIntegrationTest.testFindAreasEntries() {
        Assert.assertNotNull("Data on demand for 'Areas' failed to initialize correctly", dod.getRandomAreas());
        long count = Areas.countAreases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Areas> result = Areas.findAreasEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Areas' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Areas' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AreasIntegrationTest.testFlush() {
        Areas obj = dod.getRandomAreas();
        Assert.assertNotNull("Data on demand for 'Areas' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Areas' failed to provide an identifier", id);
        obj = Areas.findAreas(id);
        Assert.assertNotNull("Find method for 'Areas' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAreas(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Areas' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AreasIntegrationTest.testMergeUpdate() {
        Areas obj = dod.getRandomAreas();
        Assert.assertNotNull("Data on demand for 'Areas' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Areas' failed to provide an identifier", id);
        obj = Areas.findAreas(id);
        boolean modified =  dod.modifyAreas(obj);
        Integer currentVersion = obj.getVersion();
        Areas merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Areas' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AreasIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Areas' failed to initialize correctly", dod.getRandomAreas());
        Areas obj = dod.getNewTransientAreas(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Areas' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Areas' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Areas' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AreasIntegrationTest.testRemove() {
        Areas obj = dod.getRandomAreas();
        Assert.assertNotNull("Data on demand for 'Areas' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Areas' failed to provide an identifier", id);
        obj = Areas.findAreas(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Areas' with identifier '" + id + "'", Areas.findAreas(id));
    }
    
}
