// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.endusers;

import com.woomii.beta.backend.endusers.EndUsersDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EndUsersDataOnDemand_Roo_Configurable {
    
    declare @type: EndUsersDataOnDemand: @Configurable;
    
}
