// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.endusers;

import com.woomii.beta.backend.endusers.EndUsers;
import com.woomii.beta.backend.endusers.EndUsersDataOnDemand;
import com.woomii.beta.backend.endusers.EndUsersIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EndUsersIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EndUsersIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EndUsersIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EndUsersIntegrationTest: @Transactional;
    
    @Autowired
    EndUsersDataOnDemand EndUsersIntegrationTest.dod;
    
    @Test
    public void EndUsersIntegrationTest.testCountEndUserses() {
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to initialize correctly", dod.getRandomEndUsers());
        long count = EndUsers.countEndUserses();
        Assert.assertTrue("Counter for 'EndUsers' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EndUsersIntegrationTest.testFindEndUsers() {
        EndUsers obj = dod.getRandomEndUsers();
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to provide an identifier", id);
        obj = EndUsers.findEndUsers(id);
        Assert.assertNotNull("Find method for 'EndUsers' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EndUsers' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EndUsersIntegrationTest.testFindAllEndUserses() {
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to initialize correctly", dod.getRandomEndUsers());
        long count = EndUsers.countEndUserses();
        Assert.assertTrue("Too expensive to perform a find all test for 'EndUsers', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EndUsers> result = EndUsers.findAllEndUserses();
        Assert.assertNotNull("Find all method for 'EndUsers' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EndUsers' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EndUsersIntegrationTest.testFindEndUsersEntries() {
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to initialize correctly", dod.getRandomEndUsers());
        long count = EndUsers.countEndUserses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EndUsers> result = EndUsers.findEndUsersEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EndUsers' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EndUsers' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EndUsersIntegrationTest.testFlush() {
        EndUsers obj = dod.getRandomEndUsers();
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to provide an identifier", id);
        obj = EndUsers.findEndUsers(id);
        Assert.assertNotNull("Find method for 'EndUsers' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEndUsers(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EndUsers' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EndUsersIntegrationTest.testMergeUpdate() {
        EndUsers obj = dod.getRandomEndUsers();
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to provide an identifier", id);
        obj = EndUsers.findEndUsers(id);
        boolean modified =  dod.modifyEndUsers(obj);
        Integer currentVersion = obj.getVersion();
        EndUsers merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EndUsers' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EndUsersIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to initialize correctly", dod.getRandomEndUsers());
        EndUsers obj = dod.getNewTransientEndUsers(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EndUsers' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EndUsers' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EndUsersIntegrationTest.testRemove() {
        EndUsers obj = dod.getRandomEndUsers();
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EndUsers' failed to provide an identifier", id);
        obj = EndUsers.findEndUsers(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EndUsers' with identifier '" + id + "'", EndUsers.findEndUsers(id));
    }
    
}
