// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.thresholds;

import com.woomii.beta.backend.thresholds.Thresholds;
import com.woomii.beta.backend.thresholds.ThresholdsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ThresholdsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ThresholdsDataOnDemand: @Component;
    
    private Random ThresholdsDataOnDemand.rnd = new SecureRandom();
    
    private List<Thresholds> ThresholdsDataOnDemand.data;
    
    public Thresholds ThresholdsDataOnDemand.getNewTransientThresholds(int index) {
        Thresholds obj = new Thresholds();
        setMax_credits(obj, index);
        setMax_referrals(obj, index);
        return obj;
    }
    
    public void ThresholdsDataOnDemand.setMax_credits(Thresholds obj, int index) {
        int max_credits = index;
        obj.setMax_credits(max_credits);
    }
    
    public void ThresholdsDataOnDemand.setMax_referrals(Thresholds obj, int index) {
        int max_referrals = index;
        obj.setMax_referrals(max_referrals);
    }
    
    public Thresholds ThresholdsDataOnDemand.getSpecificThresholds(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Thresholds obj = data.get(index);
        Long id = obj.getId();
        return Thresholds.findThresholds(id);
    }
    
    public Thresholds ThresholdsDataOnDemand.getRandomThresholds() {
        init();
        Thresholds obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Thresholds.findThresholds(id);
    }
    
    public boolean ThresholdsDataOnDemand.modifyThresholds(Thresholds obj) {
        return false;
    }
    
    public void ThresholdsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Thresholds.findThresholdsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Thresholds' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Thresholds>();
        for (int i = 0; i < 10; i++) {
            Thresholds obj = getNewTransientThresholds(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
