// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.thresholds;

import com.woomii.beta.backend.thresholds.Thresholds;
import com.woomii.beta.backend.thresholds.ThresholdsDataOnDemand;
import com.woomii.beta.backend.thresholds.ThresholdsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ThresholdsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ThresholdsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ThresholdsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ThresholdsIntegrationTest: @Transactional;
    
    @Autowired
    ThresholdsDataOnDemand ThresholdsIntegrationTest.dod;
    
    @Test
    public void ThresholdsIntegrationTest.testCountThresholdses() {
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to initialize correctly", dod.getRandomThresholds());
        long count = Thresholds.countThresholdses();
        Assert.assertTrue("Counter for 'Thresholds' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ThresholdsIntegrationTest.testFindThresholds() {
        Thresholds obj = dod.getRandomThresholds();
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to provide an identifier", id);
        obj = Thresholds.findThresholds(id);
        Assert.assertNotNull("Find method for 'Thresholds' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Thresholds' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ThresholdsIntegrationTest.testFindAllThresholdses() {
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to initialize correctly", dod.getRandomThresholds());
        long count = Thresholds.countThresholdses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Thresholds', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Thresholds> result = Thresholds.findAllThresholdses();
        Assert.assertNotNull("Find all method for 'Thresholds' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Thresholds' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ThresholdsIntegrationTest.testFindThresholdsEntries() {
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to initialize correctly", dod.getRandomThresholds());
        long count = Thresholds.countThresholdses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Thresholds> result = Thresholds.findThresholdsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Thresholds' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Thresholds' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ThresholdsIntegrationTest.testFlush() {
        Thresholds obj = dod.getRandomThresholds();
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to provide an identifier", id);
        obj = Thresholds.findThresholds(id);
        Assert.assertNotNull("Find method for 'Thresholds' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyThresholds(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Thresholds' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ThresholdsIntegrationTest.testMergeUpdate() {
        Thresholds obj = dod.getRandomThresholds();
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to provide an identifier", id);
        obj = Thresholds.findThresholds(id);
        boolean modified =  dod.modifyThresholds(obj);
        Integer currentVersion = obj.getVersion();
        Thresholds merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Thresholds' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ThresholdsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to initialize correctly", dod.getRandomThresholds());
        Thresholds obj = dod.getNewTransientThresholds(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Thresholds' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Thresholds' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ThresholdsIntegrationTest.testRemove() {
        Thresholds obj = dod.getRandomThresholds();
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Thresholds' failed to provide an identifier", id);
        obj = Thresholds.findThresholds(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Thresholds' with identifier '" + id + "'", Thresholds.findThresholds(id));
    }
    
}
