// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.campaigns;

import com.woomii.beta.frontend.campaigns.Campaigns;
import com.woomii.beta.frontend.campaigns.CampaignsDataOnDemand;
import com.woomii.beta.frontend.campaigns.CampaignsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CampaignsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CampaignsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CampaignsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CampaignsIntegrationTest: @Transactional;
    
    @Autowired
    CampaignsDataOnDemand CampaignsIntegrationTest.dod;
    
    @Test
    public void CampaignsIntegrationTest.testCountCampaignses() {
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to initialize correctly", dod.getRandomCampaigns());
        long count = Campaigns.countCampaignses();
        Assert.assertTrue("Counter for 'Campaigns' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CampaignsIntegrationTest.testFindCampaigns() {
        Campaigns obj = dod.getRandomCampaigns();
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to provide an identifier", id);
        obj = Campaigns.findCampaigns(id);
        Assert.assertNotNull("Find method for 'Campaigns' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Campaigns' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CampaignsIntegrationTest.testFindAllCampaignses() {
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to initialize correctly", dod.getRandomCampaigns());
        long count = Campaigns.countCampaignses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Campaigns', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Campaigns> result = Campaigns.findAllCampaignses();
        Assert.assertNotNull("Find all method for 'Campaigns' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Campaigns' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CampaignsIntegrationTest.testFindCampaignsEntries() {
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to initialize correctly", dod.getRandomCampaigns());
        long count = Campaigns.countCampaignses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Campaigns> result = Campaigns.findCampaignsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Campaigns' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Campaigns' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CampaignsIntegrationTest.testFlush() {
        Campaigns obj = dod.getRandomCampaigns();
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to provide an identifier", id);
        obj = Campaigns.findCampaigns(id);
        Assert.assertNotNull("Find method for 'Campaigns' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCampaigns(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Campaigns' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CampaignsIntegrationTest.testMergeUpdate() {
        Campaigns obj = dod.getRandomCampaigns();
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to provide an identifier", id);
        obj = Campaigns.findCampaigns(id);
        boolean modified =  dod.modifyCampaigns(obj);
        Integer currentVersion = obj.getVersion();
        Campaigns merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Campaigns' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CampaignsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to initialize correctly", dod.getRandomCampaigns());
        Campaigns obj = dod.getNewTransientCampaigns(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Campaigns' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Campaigns' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CampaignsIntegrationTest.testRemove() {
        Campaigns obj = dod.getRandomCampaigns();
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Campaigns' failed to provide an identifier", id);
        obj = Campaigns.findCampaigns(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Campaigns' with identifier '" + id + "'", Campaigns.findCampaigns(id));
    }
    
}
