// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.transactions;

import com.woomii.beta.backend.transactions.Transactions;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Transactions_Roo_Configurable {
    
    declare @type: Transactions: @Configurable;
    
}
