// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.impressions;

import com.woomii.beta.backend.impressions.ImpressionsDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ImpressionsDataOnDemand_Roo_Configurable {
    
    declare @type: ImpressionsDataOnDemand: @Configurable;
    
}
