// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.impressions;

import com.woomii.beta.backend.impressions.Impressions;
import com.woomii.beta.backend.impressions.ImpressionsDataOnDemand;
import com.woomii.beta.backend.impressions.ImpressionsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ImpressionsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ImpressionsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ImpressionsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ImpressionsIntegrationTest: @Transactional;
    
    @Autowired
    ImpressionsDataOnDemand ImpressionsIntegrationTest.dod;
    
    @Test
    public void ImpressionsIntegrationTest.testCountImpressionses() {
        Assert.assertNotNull("Data on demand for 'Impressions' failed to initialize correctly", dod.getRandomImpressions());
        long count = Impressions.countImpressionses();
        Assert.assertTrue("Counter for 'Impressions' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ImpressionsIntegrationTest.testFindImpressions() {
        Impressions obj = dod.getRandomImpressions();
        Assert.assertNotNull("Data on demand for 'Impressions' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Impressions' failed to provide an identifier", id);
        obj = Impressions.findImpressions(id);
        Assert.assertNotNull("Find method for 'Impressions' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Impressions' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ImpressionsIntegrationTest.testFindAllImpressionses() {
        Assert.assertNotNull("Data on demand for 'Impressions' failed to initialize correctly", dod.getRandomImpressions());
        long count = Impressions.countImpressionses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Impressions', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Impressions> result = Impressions.findAllImpressionses();
        Assert.assertNotNull("Find all method for 'Impressions' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Impressions' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ImpressionsIntegrationTest.testFindImpressionsEntries() {
        Assert.assertNotNull("Data on demand for 'Impressions' failed to initialize correctly", dod.getRandomImpressions());
        long count = Impressions.countImpressionses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Impressions> result = Impressions.findImpressionsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Impressions' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Impressions' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ImpressionsIntegrationTest.testFlush() {
        Impressions obj = dod.getRandomImpressions();
        Assert.assertNotNull("Data on demand for 'Impressions' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Impressions' failed to provide an identifier", id);
        obj = Impressions.findImpressions(id);
        Assert.assertNotNull("Find method for 'Impressions' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyImpressions(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Impressions' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImpressionsIntegrationTest.testMergeUpdate() {
        Impressions obj = dod.getRandomImpressions();
        Assert.assertNotNull("Data on demand for 'Impressions' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Impressions' failed to provide an identifier", id);
        obj = Impressions.findImpressions(id);
        boolean modified =  dod.modifyImpressions(obj);
        Integer currentVersion = obj.getVersion();
        Impressions merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Impressions' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImpressionsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Impressions' failed to initialize correctly", dod.getRandomImpressions());
        Impressions obj = dod.getNewTransientImpressions(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Impressions' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Impressions' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Impressions' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ImpressionsIntegrationTest.testRemove() {
        Impressions obj = dod.getRandomImpressions();
        Assert.assertNotNull("Data on demand for 'Impressions' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Impressions' failed to provide an identifier", id);
        obj = Impressions.findImpressions(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Impressions' with identifier '" + id + "'", Impressions.findImpressions(id));
    }
    
}
