// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.translations;

import com.woomii.beta.frontend.translations.Translations;
import com.woomii.beta.frontend.translations.TranslationsDataOnDemand;
import com.woomii.beta.frontend.translations.TranslationsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TranslationsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TranslationsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TranslationsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TranslationsIntegrationTest: @Transactional;
    
    @Autowired
    TranslationsDataOnDemand TranslationsIntegrationTest.dod;
    
    @Test
    public void TranslationsIntegrationTest.testCountTranslationses() {
        Assert.assertNotNull("Data on demand for 'Translations' failed to initialize correctly", dod.getRandomTranslations());
        long count = Translations.countTranslationses();
        Assert.assertTrue("Counter for 'Translations' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TranslationsIntegrationTest.testFindTranslations() {
        Translations obj = dod.getRandomTranslations();
        Assert.assertNotNull("Data on demand for 'Translations' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Translations' failed to provide an identifier", id);
        obj = Translations.findTranslations(id);
        Assert.assertNotNull("Find method for 'Translations' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Translations' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TranslationsIntegrationTest.testFindAllTranslationses() {
        Assert.assertNotNull("Data on demand for 'Translations' failed to initialize correctly", dod.getRandomTranslations());
        long count = Translations.countTranslationses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Translations', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Translations> result = Translations.findAllTranslationses();
        Assert.assertNotNull("Find all method for 'Translations' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Translations' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TranslationsIntegrationTest.testFindTranslationsEntries() {
        Assert.assertNotNull("Data on demand for 'Translations' failed to initialize correctly", dod.getRandomTranslations());
        long count = Translations.countTranslationses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Translations> result = Translations.findTranslationsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Translations' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Translations' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TranslationsIntegrationTest.testFlush() {
        Translations obj = dod.getRandomTranslations();
        Assert.assertNotNull("Data on demand for 'Translations' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Translations' failed to provide an identifier", id);
        obj = Translations.findTranslations(id);
        Assert.assertNotNull("Find method for 'Translations' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTranslations(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Translations' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TranslationsIntegrationTest.testMergeUpdate() {
        Translations obj = dod.getRandomTranslations();
        Assert.assertNotNull("Data on demand for 'Translations' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Translations' failed to provide an identifier", id);
        obj = Translations.findTranslations(id);
        boolean modified =  dod.modifyTranslations(obj);
        Integer currentVersion = obj.getVersion();
        Translations merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Translations' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TranslationsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Translations' failed to initialize correctly", dod.getRandomTranslations());
        Translations obj = dod.getNewTransientTranslations(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Translations' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Translations' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Translations' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TranslationsIntegrationTest.testRemove() {
        Translations obj = dod.getRandomTranslations();
        Assert.assertNotNull("Data on demand for 'Translations' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Translations' failed to provide an identifier", id);
        obj = Translations.findTranslations(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Translations' with identifier '" + id + "'", Translations.findTranslations(id));
    }
    
}
