// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.apps;

import com.woomii.beta.frontend.apps.Apps;
import com.woomii.beta.frontend.apps.AppsDataOnDemand;
import com.woomii.beta.frontend.apps.AppsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppsIntegrationTest: @Transactional;
    
    @Autowired
    AppsDataOnDemand AppsIntegrationTest.dod;
    
    @Test
    public void AppsIntegrationTest.testCountAppses() {
        Assert.assertNotNull("Data on demand for 'Apps' failed to initialize correctly", dod.getRandomApps());
        long count = Apps.countAppses();
        Assert.assertTrue("Counter for 'Apps' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppsIntegrationTest.testFindApps() {
        Apps obj = dod.getRandomApps();
        Assert.assertNotNull("Data on demand for 'Apps' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Apps' failed to provide an identifier", id);
        obj = Apps.findApps(id);
        Assert.assertNotNull("Find method for 'Apps' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Apps' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppsIntegrationTest.testFindAllAppses() {
        Assert.assertNotNull("Data on demand for 'Apps' failed to initialize correctly", dod.getRandomApps());
        long count = Apps.countAppses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Apps', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Apps> result = Apps.findAllAppses();
        Assert.assertNotNull("Find all method for 'Apps' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Apps' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppsIntegrationTest.testFindAppsEntries() {
        Assert.assertNotNull("Data on demand for 'Apps' failed to initialize correctly", dod.getRandomApps());
        long count = Apps.countAppses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Apps> result = Apps.findAppsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Apps' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Apps' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppsIntegrationTest.testFlush() {
        Apps obj = dod.getRandomApps();
        Assert.assertNotNull("Data on demand for 'Apps' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Apps' failed to provide an identifier", id);
        obj = Apps.findApps(id);
        Assert.assertNotNull("Find method for 'Apps' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyApps(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Apps' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppsIntegrationTest.testMergeUpdate() {
        Apps obj = dod.getRandomApps();
        Assert.assertNotNull("Data on demand for 'Apps' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Apps' failed to provide an identifier", id);
        obj = Apps.findApps(id);
        boolean modified =  dod.modifyApps(obj);
        Integer currentVersion = obj.getVersion();
        Apps merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Apps' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Apps' failed to initialize correctly", dod.getRandomApps());
        Apps obj = dod.getNewTransientApps(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Apps' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Apps' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Apps' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppsIntegrationTest.testRemove() {
        Apps obj = dod.getRandomApps();
        Assert.assertNotNull("Data on demand for 'Apps' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Apps' failed to provide an identifier", id);
        obj = Apps.findApps(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Apps' with identifier '" + id + "'", Apps.findApps(id));
    }
    
}
