// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.apps;

import com.woomii.beta.frontend.apps.AppsIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AppsIntegrationTest_Roo_Configurable {
    
    declare @type: AppsIntegrationTest: @Configurable;
    
}
