// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.demographics;

import com.woomii.beta.backend.demographics.Demographics;
import com.woomii.beta.backend.demographics.DemographicsDataOnDemand;
import com.woomii.beta.backend.demographics.DemographicsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DemographicsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DemographicsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DemographicsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DemographicsIntegrationTest: @Transactional;
    
    @Autowired
    DemographicsDataOnDemand DemographicsIntegrationTest.dod;
    
    @Test
    public void DemographicsIntegrationTest.testCountDemographicses() {
        Assert.assertNotNull("Data on demand for 'Demographics' failed to initialize correctly", dod.getRandomDemographics());
        long count = Demographics.countDemographicses();
        Assert.assertTrue("Counter for 'Demographics' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DemographicsIntegrationTest.testFindDemographics() {
        Demographics obj = dod.getRandomDemographics();
        Assert.assertNotNull("Data on demand for 'Demographics' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Demographics' failed to provide an identifier", id);
        obj = Demographics.findDemographics(id);
        Assert.assertNotNull("Find method for 'Demographics' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Demographics' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DemographicsIntegrationTest.testFindAllDemographicses() {
        Assert.assertNotNull("Data on demand for 'Demographics' failed to initialize correctly", dod.getRandomDemographics());
        long count = Demographics.countDemographicses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Demographics', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Demographics> result = Demographics.findAllDemographicses();
        Assert.assertNotNull("Find all method for 'Demographics' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Demographics' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DemographicsIntegrationTest.testFindDemographicsEntries() {
        Assert.assertNotNull("Data on demand for 'Demographics' failed to initialize correctly", dod.getRandomDemographics());
        long count = Demographics.countDemographicses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Demographics> result = Demographics.findDemographicsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Demographics' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Demographics' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DemographicsIntegrationTest.testFlush() {
        Demographics obj = dod.getRandomDemographics();
        Assert.assertNotNull("Data on demand for 'Demographics' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Demographics' failed to provide an identifier", id);
        obj = Demographics.findDemographics(id);
        Assert.assertNotNull("Find method for 'Demographics' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDemographics(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Demographics' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DemographicsIntegrationTest.testMergeUpdate() {
        Demographics obj = dod.getRandomDemographics();
        Assert.assertNotNull("Data on demand for 'Demographics' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Demographics' failed to provide an identifier", id);
        obj = Demographics.findDemographics(id);
        boolean modified =  dod.modifyDemographics(obj);
        Integer currentVersion = obj.getVersion();
        Demographics merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Demographics' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DemographicsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Demographics' failed to initialize correctly", dod.getRandomDemographics());
        Demographics obj = dod.getNewTransientDemographics(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Demographics' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Demographics' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Demographics' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DemographicsIntegrationTest.testRemove() {
        Demographics obj = dod.getRandomDemographics();
        Assert.assertNotNull("Data on demand for 'Demographics' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Demographics' failed to provide an identifier", id);
        obj = Demographics.findDemographics(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Demographics' with identifier '" + id + "'", Demographics.findDemographics(id));
    }
    
}
