// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.customers;

import com.woomii.beta.frontend.customers.CustomersIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CustomersIntegrationTest_Roo_Configurable {
    
    declare @type: CustomersIntegrationTest: @Configurable;
    
}
