// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.languages;

import com.woomii.beta.frontend.languages.Languages;
import com.woomii.beta.frontend.languages.LanguagesDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LanguagesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LanguagesDataOnDemand: @Component;
    
    private Random LanguagesDataOnDemand.rnd = new SecureRandom();
    
    private List<Languages> LanguagesDataOnDemand.data;
    
    public Languages LanguagesDataOnDemand.getNewTransientLanguages(int index) {
        Languages obj = new Languages();
        setCode(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void LanguagesDataOnDemand.setCode(Languages obj, int index) {
        String code = "c" + index;
        if (code.length() > 2) {
            code = new Random().nextInt(10) + code.substring(1, 2);
        }
        obj.setCode(code);
    }
    
    public void LanguagesDataOnDemand.setName(Languages obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Languages LanguagesDataOnDemand.getSpecificLanguages(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Languages obj = data.get(index);
        Long id = obj.getId();
        return Languages.findLanguages(id);
    }
    
    public Languages LanguagesDataOnDemand.getRandomLanguages() {
        init();
        Languages obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Languages.findLanguages(id);
    }
    
    public boolean LanguagesDataOnDemand.modifyLanguages(Languages obj) {
        return false;
    }
    
    public void LanguagesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Languages.findLanguagesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Languages' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Languages>();
        for (int i = 0; i < 10; i++) {
            Languages obj = getNewTransientLanguages(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
