// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.frontend.languages;

import com.woomii.beta.frontend.languages.Languages;
import com.woomii.beta.frontend.languages.LanguagesDataOnDemand;
import com.woomii.beta.frontend.languages.LanguagesIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LanguagesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LanguagesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LanguagesIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LanguagesIntegrationTest: @Transactional;
    
    @Autowired
    LanguagesDataOnDemand LanguagesIntegrationTest.dod;
    
    @Test
    public void LanguagesIntegrationTest.testCountLanguageses() {
        Assert.assertNotNull("Data on demand for 'Languages' failed to initialize correctly", dod.getRandomLanguages());
        long count = Languages.countLanguageses();
        Assert.assertTrue("Counter for 'Languages' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LanguagesIntegrationTest.testFindLanguages() {
        Languages obj = dod.getRandomLanguages();
        Assert.assertNotNull("Data on demand for 'Languages' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Languages' failed to provide an identifier", id);
        obj = Languages.findLanguages(id);
        Assert.assertNotNull("Find method for 'Languages' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Languages' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LanguagesIntegrationTest.testFindAllLanguageses() {
        Assert.assertNotNull("Data on demand for 'Languages' failed to initialize correctly", dod.getRandomLanguages());
        long count = Languages.countLanguageses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Languages', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Languages> result = Languages.findAllLanguageses();
        Assert.assertNotNull("Find all method for 'Languages' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Languages' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LanguagesIntegrationTest.testFindLanguagesEntries() {
        Assert.assertNotNull("Data on demand for 'Languages' failed to initialize correctly", dod.getRandomLanguages());
        long count = Languages.countLanguageses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Languages> result = Languages.findLanguagesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Languages' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Languages' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LanguagesIntegrationTest.testFlush() {
        Languages obj = dod.getRandomLanguages();
        Assert.assertNotNull("Data on demand for 'Languages' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Languages' failed to provide an identifier", id);
        obj = Languages.findLanguages(id);
        Assert.assertNotNull("Find method for 'Languages' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLanguages(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Languages' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LanguagesIntegrationTest.testMergeUpdate() {
        Languages obj = dod.getRandomLanguages();
        Assert.assertNotNull("Data on demand for 'Languages' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Languages' failed to provide an identifier", id);
        obj = Languages.findLanguages(id);
        boolean modified =  dod.modifyLanguages(obj);
        Integer currentVersion = obj.getVersion();
        Languages merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Languages' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LanguagesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Languages' failed to initialize correctly", dod.getRandomLanguages());
        Languages obj = dod.getNewTransientLanguages(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Languages' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Languages' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Languages' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LanguagesIntegrationTest.testRemove() {
        Languages obj = dod.getRandomLanguages();
        Assert.assertNotNull("Data on demand for 'Languages' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Languages' failed to provide an identifier", id);
        obj = Languages.findLanguages(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Languages' with identifier '" + id + "'", Languages.findLanguages(id));
    }
    
}
