// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.demographics;

import com.woomii.beta.backend.demographics.Demographics;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Demographics_Roo_Configurable {
    
    declare @type: Demographics: @Configurable;
    
}
