// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.woomii.beta.backend.referrals;

import com.woomii.beta.backend.referrals.Referrals;
import com.woomii.beta.backend.referrals.ReferralsDataOnDemand;
import com.woomii.beta.frontend.apps.AppsDataOnDemand;
import com.woomii.beta.frontend.campaigns.CampaignsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ReferralsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReferralsDataOnDemand: @Component;
    
    private Random ReferralsDataOnDemand.rnd = new SecureRandom();
    
    private List<Referrals> ReferralsDataOnDemand.data;
    
    @Autowired
    AppsDataOnDemand ReferralsDataOnDemand.appsDataOnDemand;
    
    @Autowired
    CampaignsDataOnDemand ReferralsDataOnDemand.campaignsDataOnDemand;
    
    public Referrals ReferralsDataOnDemand.getNewTransientReferrals(int index) {
        Referrals obj = new Referrals();
        setAff_id(obj, index);
        setCreated(obj, index);
        setSandbox_mode(obj, index);
        setSuggested_friends(obj, index);
        setUa_b(obj, index);
        setUuid_a(obj, index);
        setUuid_b(obj, index);
        return obj;
    }
    
    public void ReferralsDataOnDemand.setAff_id(Referrals obj, int index) {
        String aff_id = "aff_id_" + index;
        if (aff_id.length() > 40) {
            aff_id = aff_id.substring(0, 40);
        }
        obj.setAff_id(aff_id);
    }
    
    public void ReferralsDataOnDemand.setCreated(Referrals obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void ReferralsDataOnDemand.setSandbox_mode(Referrals obj, int index) {
        Boolean sandbox_mode = Boolean.TRUE;
        obj.setSandbox_mode(sandbox_mode);
    }
    
    public void ReferralsDataOnDemand.setSuggested_friends(Referrals obj, int index) {
        short suggested_friends = new Integer(index).shortValue();
        obj.setSuggested_friends(suggested_friends);
    }
    
    public void ReferralsDataOnDemand.setUa_b(Referrals obj, int index) {
        String ua_b = "ua_b_" + index;
        if (ua_b.length() > 255) {
            ua_b = ua_b.substring(0, 255);
        }
        obj.setUa_b(ua_b);
    }
    
    public void ReferralsDataOnDemand.setUuid_a(Referrals obj, int index) {
        String uuid_a = "uuid_a_" + index;
        if (uuid_a.length() > 40) {
            uuid_a = uuid_a.substring(0, 40);
        }
        obj.setUuid_a(uuid_a);
    }
    
    public void ReferralsDataOnDemand.setUuid_b(Referrals obj, int index) {
        String uuid_b = "uuid_b_" + index;
        if (uuid_b.length() > 40) {
            uuid_b = uuid_b.substring(0, 40);
        }
        obj.setUuid_b(uuid_b);
    }
    
    public Referrals ReferralsDataOnDemand.getSpecificReferrals(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Referrals obj = data.get(index);
        Long id = obj.getId();
        return Referrals.findReferrals(id);
    }
    
    public Referrals ReferralsDataOnDemand.getRandomReferrals() {
        init();
        Referrals obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Referrals.findReferrals(id);
    }
    
    public boolean ReferralsDataOnDemand.modifyReferrals(Referrals obj) {
        return false;
    }
    
    public void ReferralsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Referrals.findReferralsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Referrals' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Referrals>();
        for (int i = 0; i < 10; i++) {
            Referrals obj = getNewTransientReferrals(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
